name: Test
on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  pull_request:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm test